# Generated by Django 4.2.10 on 2024-04-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0064_auto_20240409_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description_yjs',
            field=models.BinaryField(null=True),
        ),
    ]
